config/routes.rb
Rails.application.routes.draw do
  resources :documents, only: [:index, :create, :new, :show]
  devise_for :users
  resources :policies
  resources :companies
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "documents#index"
end

app/models/document.rb
require 'carrierwave/orm/activerecord'
class Document < ApplicationRecord
  serialize :error

  belongs_to :company
  mount_uploader :file, FileUploader

  validates :company_id, :file, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = current_user.documents.includes(:company)
  end

  def new
    @file = current_user.documents.build
  end

  def show
    @file = Document.find(params[:id])
  end

  def create
    @file = current_user.documents.build(document_params)
    if @file.save
      EmployeeCsvJob.perform_later(@file)
      redirect_to documents_path, notice: 'File Uploaded Sucessfully.'
    else
      render action: :new
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def document_params
    params.require(:document).permit(:company_id, :file)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for @file, url: documents_path do |form| %>
  <% if file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Select Company' %>
    <%= form.select :company_id, Company.all.collect {|p| [ p.name, p.id.to_i ] } %>
  </div>

  <div class="field">
    <%= form.label 'Upload CSV' %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.file %></td>
        <td><%= document.company.name %></td>
        <td><%= link_to 'Detail', document_path(document) %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Upload Comapny File', new_document_path %>

app/views/documents/new.html.erb
<h1>New File</h1>

<%= render 'form', file: @file %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file.file.path %>
</p>

<p>
  <strong>Error:</strong>
  <% if @file.error.present? %>
    <% @file.error.each do |error| %>
      <%= error %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Back', documents_path %>